### ISSUE TITLE
Change / Set View?

### ISSUE THREAD

**Issue by IgnacioAC** [iosdeveloper/InfiniTabBar#3]
How I can relate and change a view controller? I can not find the way

Thanks

**Comment by iosdeveloper** [comment]
It is an UITabBar not an UITabBarController replacement.

**Comment by IgnacioAC** [comment]
Then I can not associate it with a view?

**Comment by iosdeveloper** [comment]
Nope. You could however try to set your InfiniTabBar instance as tabBar property of your UITabBarController (UNTESTED!).
